repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-ast
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: ''
    hooks:
      - id: autopep8