name: Build and Test on Push or PR
on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test-n-publish:
    name: Build and publish Python distributions to PyPI and TestPyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Install pypa/build
        run: >-
          python -m
          pip install
          build
          --user
      - name: Install pytest
        run: |
          python -m pip install pytest
          python -m pip install -r requirements.txt
      - name: Build a binary wheel and a source tarball
        run: >-
          python -m
          build
          --sdist
          --wheel
          --outdir dist/
      - name: Test with Pytest
        run: |
          python -m pytest
