name: Build and Test on Push or PR
on: 
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  build-test-n-publish:
    name: Build and test Python distributions on push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.10.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.10.8
      - name: Install pypa/build
        run: >-
          python -m
          pip install
          build
          --user
      - name: Install pytest
        run: |
          python -m pip install pytest
          python -m pip install -r requirements.txt
      - name: Build a binary wheel and a source tarball
        run: >-
          python -m
          build
          --sdist
          --wheel
          --outdir dist/
      - name: Install Build for Testing
        run: |
          python -m pip install dist/dash-tools-*.tar.gz
      - name: Test with Pytest
        run: |
          python -m pytest
