name: Create Tag & Release
on: 
  push:
    branches: [main]

jobs:
  build:
    name: Create Tag & Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          echo DASHTOOLS_VERSION=$(awk -F'=' '/^__version__/ {gsub(/^[ \t]+|[ \t]+$/, "", $2); print $2}' src/dashtools/version.py | sed "s/'//g") >> $GITHUB_ENV
      - name: Push new tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          custom_tag: ${{ env.DASHTOOLS_VERSION }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: v${{ env.DASHTOOLS_VERSION }}
          release_name: Version ${{ env.DASHTOOLS_VERSION }}
          run: echo CHANGELOG_VERSION="$(./docs/source/print_version.sh)"  >> $GITHUB_ENV
          body: ${{ env.CHANGELOG_VERSION }}
          draft: true # Set to false to auto publish
          prerelease: false