name: Build Test and Upload to PyPi on Release
on: 
  release:
    types: [created]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-test-n-publish:
    name: Build test and publish Python distributions to PyPI on release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Install pypa/build
        run: >-
          python -m
          pip install
          build
          --user
      - name: Install pytest
        run: |
          python -m pip install pytest
          python -m pip install -r requirements.txt
      - name: Build a binary wheel and a source tarball
        run: >-
          python -m
          build
          --sdist
          --wheel
          --outdir dist/
      - name: Install Build for Testing
        run: |
          python -m pip install dist/dash-tools-*.tar.gz
      - name: Test with Pytest
        run: |
          python -m pytest
      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: Github Actions job result
          to: andrew_hossack@outlook.com
          from: GitHub Actions
          secure: true
          body: PyPi deploy job of ${{github.repository}} completed successfully!
          ignore_cert: true
          priority: normal
